/* Generates the gitignored config.js from .env (local) or from process.env
   (Vercel build). Reads only the three values the browser needs — never
   SECRET_KEY, never DATABASE_URL. Run: node tools/make-config.mjs */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';

function parseEnv(text) {
  const out = {};
  for (const line of text.split('\n')) {
    const s = line.trim();
    if (!s || s.startsWith('#') || !s.includes('=')) continue;
    const i = s.indexOf('=');
    out[s.slice(0, i).trim()] = s.slice(i + 1).trim().replace(/^["']|["']$/g, '');
  }
  return out;
}

const fileEnv = existsSync('.env') ? parseEnv(readFileSync('.env', 'utf8')) : {};
const pick = (k) => process.env[k] || fileEnv[k] || '';

/* Supabase's dashboard hands you the project URL with /rest/v1/ already on
   the end. sync.js appends that path itself, so leaving it produces
   /rest/v1//rest/v1/... and every request fails with PGRST125. */
const base = pick('PROJECT_URL').replace(/\/+$/, '').replace(/(\/rest(\/v1)?)+$/, '');

const out = `/* GENERATED by tools/make-config.mjs — do not edit, do not commit.
   Regenerate with: npm run config */
export const SUPABASE_URL = ${JSON.stringify(base)};
export const SUPABASE_ANON_KEY = ${JSON.stringify(pick('PUBLIC_KEY'))};
export const USER_ID = ${JSON.stringify(pick('USER_ID'))};
`;

writeFileSync('config.js', out);
const missing = ['PROJECT_URL', 'PUBLIC_KEY', 'USER_ID'].filter((k) => !pick(k));
console.log(missing.length
  ? `config.js written; MISSING ${missing.join(', ')} — the app will run local-only`
  : 'config.js written with all three values');
