/* Generates the gitignored config.js from .env (local) or from process.env
   (Vercel build). Reads only the three values the browser needs — never
   SECRET_KEY, never DATABASE_URL. Run: node tools/make-config.mjs

   parseEnv is exported and covered by test/config.test.js. Generation only
   runs when this file is executed directly, so importing it is inert. */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { pathToFileURL } from 'node:url';

/* Standard dotenv semantics, and deliberately tolerant of a .env whose lines
   were pasted back out of the generated config.js — which is exactly the
   shape this project's own output has:

       SUPABASE_URL ="https://….supabase.co";

   The old implementation stripped one leading and one trailing quote with a
   regex. Here the trailing character is ';', not '"', so the closing quote
   survived and every value came back with a '";' glued to the end: the URL
   404'd, the key was two characters too long, and the UUID stopped matching,
   which RLS rejects. That is worse than failing outright, because the app
   then believes it is configured. So: a quoted value ends at its matching
   closing quote and anything after that is discarded, and an unquoted value
   gives up one trailing ';' — never part of a real URL, key or UUID. */
export function parseEnv(text) {
  const out = {};
  for (const line of String(text).split('\n')) {
    const s = line.trim();
    if (!s || s.startsWith('#') || !s.includes('=')) continue;
    const i = s.indexOf('=');            /* first '=' only: values may contain more */
    const key = s.slice(0, i).trim();
    if (!key) continue;
    let value = s.slice(i + 1).trim();
    const quote = value[0];
    if (quote === '"' || quote === "'") {
      const end = value.indexOf(quote, 1);
      /* An unterminated quote is a typo, not a value — keep the rest rather
         than dropping the line, but do not hunt for a closer that is absent. */
      value = end === -1 ? value.slice(1) : value.slice(1, end);
    } else {
      value = value.replace(/\s*;$/, '');
    }
    out[key] = value;
  }
  return out;
}

/* Each browser value has two accepted spellings. The Supabase dashboard calls
   them PROJECT_URL and PUBLIC_KEY; its own client snippets and most of the
   ecosystem call them SUPABASE_URL and SUPABASE_ANON_KEY. A .env written from
   either source has to work, so every name is tried in turn — process.env
   first for both, because a Vercel build variable should beat a checked-out
   file. Nothing here reads or emits SECRET_KEY or DATABASE_URL. */
export const URL_KEYS = ['PROJECT_URL', 'SUPABASE_URL'];
export const KEY_KEYS = ['PUBLIC_KEY', 'SUPABASE_ANON_KEY'];

function generate() {
  const fileEnv = existsSync('.env') ? parseEnv(readFileSync('.env', 'utf8')) : {};
  const pickOne = (k) => process.env[k] || fileEnv[k] || '';
  const pick = (...names) => {
    for (const n of names) {
      const v = pickOne(n);
      if (v) return v;
    }
    return '';
  };

  /* Supabase's dashboard hands you the project URL with /rest/v1/ already on
     the end. sync.js appends that path itself, so leaving it produces
     /rest/v1//rest/v1/... and every request fails with PGRST125. */
  const base = pick(...URL_KEYS).replace(/\/+$/, '').replace(/(\/rest(\/v1)?)+$/, '');

  writeFileSync('config.js', `/* GENERATED by tools/make-config.mjs — do not edit, do not commit.
   Regenerate with: npm run config */
export const SUPABASE_URL = ${JSON.stringify(base)};
export const SUPABASE_ANON_KEY = ${JSON.stringify(pick(...KEY_KEYS))};
export const USER_ID = ${JSON.stringify(pick('USER_ID'))};
`);

  /* Name the whole accepted pair in the warning, so someone whose .env uses
     the other spelling is not sent looking for a variable they deliberately
     did not set. */
  const missing = [URL_KEYS, KEY_KEYS, ['USER_ID']]
    .filter((names) => !pick(...names))
    .map((names) => names.join(' or '));
  console.log(missing.length
    ? `config.js written; MISSING ${missing.join('; ')} — the app will run local-only`
    : 'config.js written with all three values');
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) generate();
