/* Generates the gitignored config.js from .env (local) or from process.env
   (Vercel build). Reads only the three values the browser needs — never
   SECRET_KEY, never DATABASE_URL. Run: node tools/make-config.mjs */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';

function parseEnv(text) {
  const out = {};
  for (const line of text.split('\n')) {
    const s = line.trim();
    if (!s || s.startsWith('#') || !s.includes('=')) continue;
    const i = s.indexOf('=');
    out[s.slice(0, i).trim()] = s.slice(i + 1).trim().replace(/^["']|["']$/g, '');
  }
  return out;
}

const fileEnv = existsSync('.env') ? parseEnv(readFileSync('.env', 'utf8')) : {};

/* Each browser value has two accepted spellings. The Supabase dashboard calls
   them PROJECT_URL and PUBLIC_KEY; its own client snippets and most of the
   ecosystem call them SUPABASE_URL and SUPABASE_ANON_KEY. A .env written from
   either source has to work, so every name is tried in turn — process.env
   first for both, because a Vercel build variable should beat a checked-out
   file. Values are read one level up, in `pick`; nothing here reads or emits
   SECRET_KEY or DATABASE_URL. */
const pickOne = (k) => process.env[k] || fileEnv[k] || '';
const pick = (...names) => {
  for (const n of names) {
    const v = pickOne(n);
    if (v) return v;
  }
  return '';
};

const URL_KEYS = ['PROJECT_URL', 'SUPABASE_URL'];
const KEY_KEYS = ['PUBLIC_KEY', 'SUPABASE_ANON_KEY'];

/* Supabase's dashboard hands you the project URL with /rest/v1/ already on
   the end. sync.js appends that path itself, so leaving it produces
   /rest/v1//rest/v1/... and every request fails with PGRST125. */
const base = pick(...URL_KEYS).replace(/\/+$/, '').replace(/(\/rest(\/v1)?)+$/, '');

const out = `/* GENERATED by tools/make-config.mjs — do not edit, do not commit.
   Regenerate with: npm run config */
export const SUPABASE_URL = ${JSON.stringify(base)};
export const SUPABASE_ANON_KEY = ${JSON.stringify(pick(...KEY_KEYS))};
export const USER_ID = ${JSON.stringify(pick('USER_ID'))};
`;

writeFileSync('config.js', out);
/* Name the whole accepted pair in the warning, so someone whose .env uses the
   other spelling is not sent looking for a variable they deliberately did not
   set. */
const missing = [URL_KEYS, KEY_KEYS, ['USER_ID']]
  .filter((names) => !pick(...names))
  .map((names) => names.join(' or '));
console.log(missing.length
  ? `config.js written; MISSING ${missing.join('; ')} — the app will run local-only`
  : 'config.js written with all three values');
